In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# VISUALISATION (sur la base du TD2)

## 1. Charger l'ensemble des csv

In [2]:
class ReadCSV:
    def __init__(self, path):
        file = open(path)
        self.path = path
        self.file = file
        self.data = pd.read_csv(file, encoding="utf-8", skipinitialspace=True)

    def Z(self):
        data = self.data
        # Remove U-FFFD.
        data["Label"] = data["Label"].str.replace(" � ", ": ")
        # Remove Inf & NaN.
        data.replace([np.inf, -np.inf], np.nan, inplace=True)
        data = data.dropna(axis=0, how="any")
        # Remove object columns.
        pre_X = data.iloc[:, :-1]
        pre_y = data["Label"]
        for c in pre_X.loc[:, pre_X.dtypes == object]:
            pre_X.drop(columns=c, inplace=True)
        # Convert to float & remove Inf & NaN.
        pre_X = pre_X.astype(np.float)
        pre_X.replace([np.inf, -np.inf], np.nan, inplace=True)
        pre_X["Label"] = pre_y.values
        Z = pre_X.dropna(axis=0, how="any")
        # Output.
        X = Z.iloc[:, :-1]
        y = Z["Label"]
        X = np.asarray(X).astype(np.float)
        return X, y

In [3]:
Z1 = ReadCSV(
    "../Data/MachineLearningCVE/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv"
).Z()
Z2 = ReadCSV(
    "../Data/MachineLearningCVE/Friday-WorkingHours-Morning.pcap_ISCX.csv").Z(
    )
X = np.concatenate((Z1[0], Z2[0]))
y = np.concatenate((Z1[1], Z2[1]))

Les questions suivantes sont à appliquer aux algorithmes "decision tree", "random forest", et "svm". On suppose que les datasets train/test sont en proportion 70%/30%

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print(X_train.shape, X_test.shape)

(252945, 76) (108406, 76)


In [5]:
class Score:
    def __init__(self, y_true, y_pred):
        self.true = y_true
        self.pred = y_pred

    def confusion(self):
        return confusion_matrix(self.true, self.pred)

    def accuracy(self):
        return accuracy_score(self.true, self.pred)

    def precision(self):
        return precision_score(self.true, self.pred, average='weighted')

    def recall(self):
        return recall_score(self.true, self.pred, average='weighted')

In [6]:
dt = DecisionTreeClassifier().fit(X_train, y_train)

In [7]:
rf = DecisionTreeClassifier().fit(X_train, y_train)

In [ ]:
# svm = SVC(gamma="auto").fit(X_train, y_train)

## 2. Afficher les matrices de confusion et interpréter, avec les paramètres des algorithmes par défaut

In [8]:
print(np.unique(y), "\n")
print(Score(y_test, dt.predict(X_test)).confusion(), "\n")
print(Score(y_test, rf.predict(X_test)).confusion())

['BENIGN' 'Bot' 'Web Attack: Brute Force' 'Web Attack: Sql Injection'
 'Web Attack: XSS'] 

[[107118      7      8      3      5]
 [    13    602      0      0      0]
 [     4      0    345      0    112]
 [     2      0      0      1      0]
 [     3      0     98      0     85]] 

[[107115     11      7      2      6]
 [    11    604      0      0      0]
 [     5      0    346      1    109]
 [     1      0      0      2      0]
 [     4      0    101      0     81]]


## 3. Pour une liste de valeur d'un paramètre choisi (*), calculer les métriques suivantes et les afficher (métrique = f(paramètre)):

- accuracy

- precision

- recall

(*) paramètres "max_depth" pour decision tree et random forest, "n_estimators" aussi pour random forest, "kernel" pour SVM

In [9]:
print(Score(y_test, dt.predict(X_test)).accuracy())
print(Score(y_test, rf.predict(X_test)).accuracy(), "\n")
print(Score(y_test, dt.predict(X_test)).precision())
print(Score(y_test, rf.predict(X_test)).precision(), "\n")
print(Score(y_test, dt.predict(X_test)).recall())
print(Score(y_test, rf.predict(X_test)).recall())

0.9976477316753686
0.9976200579303729 

0.9977178184167148
0.9976698814515633 

0.9976477316753686
0.9976200579303729


## 4. Faire un choix de paramètres intéressant (un choix par algorithme), en le justifiant. Pour ce choix, afficher la matrice de confusion correspondante et la comparer à celle de la question 2.

## 5. Pour ce même choix, faire varier les proportions train/test par tranche de 10% (10%/90%, 20%/80%, ...) et observer le comportement des métriques de la question 3. Interpréter.

# TENSOR-FLOW

## 1. Installer tensor-flow

## 2. Faire tourner le code du tutoriel suivant (reconstruction d'images avec un autoencoder):

https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/3_NeuralNetworks/autoencoder.py

In [13]:
# exec(open("autoencoder.py").read())

# QUESTION

Comment pourrait-on adapter le tuto autoencoder de tensor-flow pour analysre nos données réseaux ?